server:
  port: 8443
  ssl:
    enabled: true
    key-alias: colombia
    key-store: src/main/resources/saml/colombia.jks
    key-store-password: colombia-password

logging:
  level:
    org.springframework.security: DEBUG